#! /usr/bin/env sh

# install input-source-switcher

echo 'clone input-source-switcher'
git submodule update --init --recursive

echo 'compile and install input-source-switcher'
cd input-source-switcher
mkdir -p build && cd build
cmake ..
make
make install
